### PR TITLE
Verify and authorize JWTs with API endpoints

### PR DESCRIPTION
**Pull request by davidallendj**
# Summary and Scope

This PR adds implements middleware to verify and authorize JWTs using a [`go-chi`](https://github.com/go-chi/chi) router similar to this example: https://github.com/go-chi/jwtauth. Therefore, when enabled, *no requests can be made to any of the protected API endpoints* (which is currently all of them). Attempting to do so, will return a 

Additionally, this PR effectively replaces `gorilla/mux` with `go-chi/mux` for it's middleware capabilities and other useful features. The JWT verification is disable by default to maintain the original behavior of SMD, but can be enabled by using a new `--require-auth` flag added. The authorization has been tested to require a token when the flag is passed so far.

# Testing

- M2 Sonoma 14.2 MacOS
- Run the following commands after cloning [this](https://github.com/davidallendj/deployment-recipes/tree/smd-auth) repo:
  - Clone repo and change branch: `git clone git@github.com:davidallendj/deployment-recipes.git && cd deployment-recipes && git checkout smd-auth`
  - Build the SMD binaries: `rm smd* && make binaries`
  - Build local docker image to test with `smd-auth` branch: `docker build --tag smd:testing .`
  - Start up services: `docker compose -f ochami-services.testing.yml -f ochami-krakend-ce.yml -f hydra.yml up`
  - Follow tutorial to create client and get bearer token: https://www.ory.sh/docs/hydra/5min-tutorial
  - Extract access token from TOKEN variable: `ACCESS_TOKEN=$(echo $TOKEN | jq -r '.access_token'`
  - Perform request to SMD (or other client) with bearer token: `curl http://$SMD_HOST/hsm/v2/service/ready -H "Authorization: BEARER $ACCESS_TOKEN`
# TODO
- ~~Verify that a valid token allows using the SMD API~~

### CODE REVIEW

**Comment by alexlovelltroy** [comment]
Reading through the implementation, this appears to add the jwt validation to every handler, including the healthchecks.  I don't think a jwt should be required to detect that a service is functional.

Is it possible to maintain a pair of routers instead of a single one to allow us to apply different middleware to the status/liveness checks from the main routes?

**Comment by davidallendj** [comment]
It's possible to expose public routes with the same router so the health checks don't require validation.

**Comment by davidallendj** [comment]
After thinking about it for a little while, I think I don't have to change the struct at all. I think a better approach would be to split the `generateRoutes` function into `generatePublicRoutes` and `generateProtectedRoutes` and set them up each accordingly.

**Comment by alexlovelltroy** [comment]
That sounds perfectly reasonable and preserves the ability for health/liveness checks to work properly

**Review by alexlovelltroy — APPROVED** [review]
LGTM

**Pull request merged**
