### PR TITLE
Added OpenCHAMI middleware to router.NewRouter()

### PR DESCRIPTION
**Pull request by davidallendj**
Addresses #27 by adding the OpenCHAMI middleware.

### CODE REVIEW

**Comment by davidallendj** [comment]
Seems that the OpenCHAMI `JWTAuth` used with `AuthenticatorWithRequiredClaims` is not compatible with the one being used with `github.com/OpenCHAMI/jwtauth/v5` and the PR that adds the `jwt.NewKeySet` and JWKS functionality has not be merged upstream yet (https://github.com/go-chi/jwtauth/pull/85).

**Comment by synackd** [comment]
Is the functionality in that upstream PR able to be put into the OpenCHAMI jwtauth for now?

**Comment by davidallendj** [comment]
> Is the functionality in that upstream PR able to be put into the OpenCHAMI jwtauth for now?

I think the OpenCHAMI jwtauth already has that functionality. I think we would just have to change the import in the OpenCHAMI middleware to point to the OpenCHAMI jwtauth for now and then rebase it to upstream go-chi. Once it finally gets merged, we can change the import back to upstream and then delete the OpenCHAMI one.

**Comment by synackd** [comment]
OK. Is this ready to be tested?

**Review by alexlovelltroy — APPROVED** [review]
LGTM

**Comment by davidallendj** [comment]
> OK. Is this ready to be tested?

Looks like SMD is ready, but we'll have to switch the authenticator to use the OpenCHAMI jwtauth for now.

**Comment by synackd** [comment]
I'm getting this error when building:

```
# github.com/OpenCHAMI/smd/v2/cmd/smd
cmd/smd/routers.go:72:61: cannot use s.tokenAuth (variable of type *"github.com/OpenCHAMI/jwtauth/v5".JWTAuth) as *"github.com/go-chi/jwtauth/v5".JWTAuth value in argument to openchami_authenticator.AuthenticatorWithRequiredClaims
cmd/smd/auth.go:13:2: "github.com/lestrrat-go/jwx/jwt" imported and not used
make: *** [Makefile:55: smd] Error 1
```

**Comment by synackd** [comment]
Looks like switching the import to use the OpenCHAMI jwtauth will solve this as discussed [here](https://github.com/OpenCHAMI/bss/pull/47#issuecomment-2284999014).

**Comment by synackd** [comment]
SMD is now building with those changes.

**Review by synackd — APPROVED** [review]
Tested working. LGTM!

**Pull request merged**
