### PR TITLE
Add new parsing function to handle new inventory data format

### PR DESCRIPTION
**Pull request by davidallendj**
This PR adds a new `parseRedfishPostDataV2()` function to parse a new format of data expected to be received from `magellan`. This function will achieve the same parity as the original parsing function and possible include more information when and if necessary. 

The function expects data in the following format:
```json
{
    "FQDN": "https://...",
    "ID": "...",
    "MACRequired": true,
    "Name": "",
    "RediscoverOnUpdate": false,
    "Systems": [
        {
            "uri": "https://.../redfish/v1/Systems/Self",
            "manufacturer": "...",
            "name": "System",
            "model": "...",
            "serial": "...",
            "bios_version": "...",
            "ethernet_interfaces": [
                {
                    "uri": "https://.../redfish/v1/Systems/Self/EthernetInterfaces/Offboard_0_0",
                    "mac": "...",
                    "name": "..."
                },
                {
                    "uri": "https://.../redfish/v1/Systems/Self/EthernetInterfaces/Onboard_0_1",
                    "mac": "...",
                    "ip": "0.0.0.0",
                    "name": "..."
                },
            ],
            "network_interfaces": [
                {
                    "uri": "https://.../redfish/v1/Systems/Self/NetworkInterfaces/Onboard_0",
                    "name": "...",
                    "description": "NIC 1",
                    "adapter": {
                        "uri": "https://.../redfish/v1/Chassis/Self/NetworkAdapters/Onboard_0",
                        "name": "..."
                    }
                },
            ],
            "power_state": "On",
            "processor_count": 1,
            "processor_type": "...",
            "memory_total": 128
        },
    ],
    "Type": "",
    "User": "foo"
}
```

### CODE REVIEW

**Comment by synackd** [comment]
Cool! So as of this writing, `parseRedfishPostDataV2()` isn't called by anything yet and we need to figure out how/when to call it over the old function, `parseRedfishPostData()`. Since this is technically an incompatible API change, we probably want to roll it out slowly. There are a couple of ways that @davidallendj and I discussed doing this that  we'd like discussion from the reviewers on:

1. Use a flag (e.g. `--rfev2`) that tells SMD to use `parseRedfishPostDataV2()` over `parseRedfishPostData()`.
2. Use a custom header to tell SMD to use `parseRedfishPostDataV2()` to parse the POST request over `parseRedfishPostData()`.

For 1, all requests would use the new data format when SMD is run with the flag. For 2, the new format is only used if the header is set in the POST request. I'm not sure I see a use case for 2 to be able to include both formats except for debugging purposes so I lean more towards 1, but I am interested in seeing what the reviewers think.

Whichever method is chosen, @davidallendj and I agreed that introducing this change in a way that allows both functions to be used/interchanged and doesn't change the API (yet) is the way to introduce this change.

**Comment by alexlovelltroy** [comment]
I suggest we explicitly version the data payload using jsonschema and then have the same endpoint read the version info and do the right thing.

**Comment by alexlovelltroy** [comment]
@davidallendj I'm not sure what to do with this PR.  

If you want us to merge it quickly so you can do a release, I recommend backing off the last commit so the behavior remains unchanged for the moment.

If you want to continue with implementation of [RFD 39](https://github.com/OpenCHAMI/roadmap/issues/39), I think this needs a few other pieces:

- [ ] Import from the [schemas repo](https://github.com/openchami/schemas) so you aren't re-declaring these common structs.
- [ ] Make the default behavior of SMD without the named/versioned schema to use the old internal schema for now.  Updating the default should be considered a breaking change.
- [ ] Update the tests to ensure that clients get good failure information when a payload doesn't meet the schema definition.
- [ ] This will need to merge and release before Magellan can be changed to do the same thing unless we add feature flagging to Magellan now and change the default in the next version bump.

**Comment by davidallendj** [comment]
This just needs to be tested before merging now to make sure that it works.

**Comment by davidallendj** [comment]
Confirmed that the new parsing code works with the new `magellan` data format using v0.1.3.

**Comment by davidallendj** [comment]
> @davidallendj I'm not sure what to do with this PR.
> 
> If you want us to merge it quickly so you can do a release, I recommend backing off the last commit so the behavior remains unchanged for the moment.
> 
> If you want to continue with implementation of [RFD 39](https://github.com/OpenCHAMI/roadmap/issues/39), I think this needs a few other pieces:
> 
> * [ ]  Import from the [schemas repo](https://github.com/openchami/schemas) so you aren't re-declaring these common structs.
> * [x]  Make the default behavior of SMD without the named/versioned schema to use the old internal schema for now.  Updating the default should be considered a breaking change.
> * [ ]  Update the tests to ensure that clients get good failure information when a payload doesn't meet the schema definition.
> * [ ]  This will need to merge and release before Magellan can be changed to do the same thing unless we add feature flagging to Magellan now and change the default in the next version bump.

We're going to address each of these tasks in a new PR after this one gets merged. That way, we will have a version of SMD that is compatible with the new data format, and then we can make more improvements behind the scenes afterwards.

**Comment by davidallendj** [comment]
@alexlovelltroy Just waiting on @synackd to finish testing. Once he's done, we can merge.

**Review by synackd — APPROVED** [review]
Tested on a couple of clusters and even found some issues to fix in Magellan. LGTM.

**Pull request merged**
